export const FETCH_LESSONS_REQUEST = 'FETCH_LESSONS_REQUEST';
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS';
export const FETCH_LESSONS_FAILURE = 'FETCH_LESSONS_FAILURE';

export const FETCH_LESSONDATAUSER_REQUEST = 'FETCH_LESSONDATAUSER_REQUEST';
export const FETCH_LESSONDATAUSER_SUCCESS = 'FETCH_LESSONDATAUSER_SUCCESS';
export const FETCH_LESSONDATAUSER_FAILURE = 'FETCH_LESSONDATAUSER_FAILURE';