// songs
export const FETCH_SONG_REQUEST = 'FETCH_SONG_REQUEST';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';
export const FETCH_SONG_FAILURE = 'FETCH_SONG_FAILURE';

// song details
export const FETCH_SONGDETAIL_REQUEST = 'FETCH_SONGDETAIL_REQUEST';
export const FETCH_SONGDETAIL_SUCCESS = 'FETCH_SONGDETAIL_SUCCESS';
export const FETCH_SONGDETAIL_FAILURE = 'FETCH_SONGDETAIL_FAILURE';

// fav songs 
export const FETCH_FAVSONGS_REQUEST = 'FETCH_FAVSONGS_REQUEST';
export const FETCH_FAVSONGS_SUCCESS = 'FETCH_FAVSONGS_SUCCESS';
export const FETCH_FAVSONGS_FAILURE = 'FETCH_FAVSONGS_FAILURE';

export const REMOVE_FAVSONG_REQUEST = 'REMOVE_FAVSONG_REQUEST';
export const REMOVE_FAVSONG_SUCCESS = 'REMOVE_FAVSONG_SUCCESS';
export const REMOVE_FAVSONG_FAILURE = 'REMOVE_FAVSONG_FAILURE';

export const ADD_FAVSONG_REQUEST = 'ADD_FAVSONG_REQUEST';
export const ADD_FAVSONG_SUCCESS = 'ADD_FAVSONG_SUCCESS';
export const ADD_FAVSONG_FAILURE = 'ADD_FAVSONG_FAILURE';