export const FETCH_SONG_REQUEST = 'FETCH_SONG_REQUEST';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';
export const FETCH_SONG_FAILURE = 'FETCH_SONG_FAILURE';

export const FETCH_SONGDETAIL_REQUEST = 'FETCH_SONGDETAIL_REQUEST';
export const FETCH_SONGDETAIL_SUCCESS = 'FETCH_SONGDETAIL_SUCCESS';
export const FETCH_SONGDETAIL_FAILURE = 'FETCH_SONGDETAIL_FAILURE';
