export const API_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvdnFjanVmbWJ0dmxodmJndG1xIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4NjM4MDQyOCwiZXhwIjoyMDAxOTU2NDI4fQ.eb-GSdKXqLszfxeb1Z2unipKOjKXpiy9Ej1WUcsTO4g';

